#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;

require_once __DIR__ . '/wp-load.php';

// save current directory
$dir = getcwd();
// Change to root dir
chdir(__DIR__);

/** @var Application $application */
$application = gpx(Application::class);

/** @var ConsoleOutput $output */
$output = gpx(ConsoleOutput::class);

// Run CLI Application
$status = $application->run(null, $output);

// Print a new line
echo PHP_EOL;
// reset directory
chdir($dir);
exit($status);
